baby_snap_2/baby_snap_2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('snap_test_2.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

baby_snap_2/snap_test_2/urls.py
from django.conf.urls import url
#from .models import SnapLocations
from . import views


urlpatterns = [
    url(r'^home$', views.home),
    url(r'^ajax/get_places/$', views.get_places),
    url(r'^groceries/(?P<store_id>\w+)/$', views.submit_grocery_list, name='grocery_list'),
    url(r'^ajax/cash_register/$', views.cash_register, name='cash_register'),
    url(r'^submit-prices$', views.submit_prices, name='submit_prices'),
    url(r'^submit-prices/(?P<store_id>\w+)/(?P<food_string>[\d+&?]+)/$', views.submit_prices, name='price_page'),
    url(r'^submit-prices/(?P<store_id>\w+)/$', views.submit_prices_blank, name='blank_price_page'),
    url(r'^ajax/update_price/$', views.update_price, name='update_price')
]

baby_snap_2/snap_test_2/models.py
from django.db import models
from django.contrib.gis.db import models as gismodels
from django.utils import timezone
from django.forms import ModelForm
from django.contrib.auth.models import User

class SnapLocations(models.Model):
    store_id = models.IntegerField()
    double_value = models.CharField(max_length = 5000)
    farmers_mkt = models.BooleanField()
    store_name = models.CharField(max_length = 5000)
    address = models.CharField(max_length = 5000)
    place_id = models.CharField(max_length = 5000)
    geom = gismodels.PointField()
    phone = models.CharField(max_length = 5000)
    hours = models.CharField(max_length = 5000)
    website = models.URLField(max_length = 5000)
    rating = models.FloatField()
    store_category = models.CharField(max_length = 5000)
    price_level = models.CharField(max_length = 5000)

    # Returns the string representation of the model.
    def __str__(self):              
        return self.store_name

class FoodPrices(models.Model):
    food_name = models.CharField(max_length=100)
    food_quantity = models.CharField(max_length=20)
    food_price = models.FloatField()
    date_last_updated = models.DateTimeField(default=timezone.now)
    food_type = models.CharField(max_length=50, default=0)
    # Returns the string representation of the model.
    def __str__(self):              
        return self.food_name

class Multipliers(models.Model):
    # Store Regression Estimates:
    store_category = models.CharField(max_length = 50)
    price_level = models.CharField(max_length = 50)
    multiplier = models.FloatField()

class StorePriceModel(models.Model):
    store_id = models.IntegerField()
    food_id = models.IntegerField()
    n = models.IntegerField()
    users_mean = models.FloatField()

class UserData(models.Model):
    store_id = models.IntegerField()
    food_id = models.IntegerField()
    user_price = models.FloatField()

baby_snap_2/snap_test_2/forms.py
from django import forms
from .models import FoodPrices

#Inspired by ui in pa3
def types_list(lst):
    return [(x,x) for x in lst]
    
class FilterForm(forms.Form):
    types = types_list(['Grocery',"Farmer's Market", 'Convenience Store', 'Gas Station', 'Other'])
    retailer_type = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=types, label='Retailer Type', required = False)
    
    dollar_signs = types_list(["$","$$","$$$", "$$$$"])
    price = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), choices=dollar_signs, label='Price', required = False)
     
    stars = [(0,""), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
    rating = forms.ChoiceField(choices=stars, label='Average Rating', required = False)

    participating = types_list(['Participating locations'])
    double_value = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple(), label = "Double Value Coupon Program (farmers markets only)", required=False, choices= participating)

class PricesForm(forms.Form):
    name = forms.CharField( widget=forms.HiddenInput(attrs={'id':'name'}))
    retailer_type = forms.CharField( widget=forms.HiddenInput(attrs={'id':'retailer_type'}))
    price = forms.CharField( widget=forms.HiddenInput(attrs={'id':'price'}))
    place_id = forms.CharField( widget=forms.HiddenInput(attrs={'id':'place_id'}))


class GroceryForm(forms.ModelForm):
    
    fruits_and_veggies = forms.ModelChoiceField(queryset=FoodPrices.objects.filter(food_type="Fruits & Vegetables").order_by('food_name'), \
        empty_label = "Fruits & Vegetables", label="", required=False)

    meat_and_fish = forms.ModelChoiceField(queryset=FoodPrices.objects.filter(food_type="Meat & Fish").order_by('food_name'), \
        empty_label = "Meat & Fish", label="", required=False)
    
    dairy = forms.ModelChoiceField(queryset=FoodPrices.objects.filter(food_type="Dairy").order_by('food_name'), \
        empty_label = "Dairy", label="", required=False)

    grains = forms.ModelChoiceField(queryset=FoodPrices.objects.filter(food_type="Grains").order_by('food_name'), \
        empty_label = "Grains", label="", required=False)

    other = forms.ModelChoiceField(queryset=FoodPrices.objects.filter(food_type="Other").order_by('food_name'), \
        empty_label = "Other", label="", required=False)
    
    class Meta:
        model = FoodPrices
        exclude = ['food_name', 'food_quantity', 'food_price', 'date_last_updated', 'food_type']

    

baby_snap_2/snap_test_2/views.py
from .models import SnapLocations, FoodPrices
from .forms import PricesForm, GroceryForm, FilterForm
from . import placesAPI as pa
from . import pricesAPI as pricesAPI

from django.shortcuts import render
from django.core.serializers import serialize
from django.http import JsonResponse
from django.contrib.gis.geos import Polygon


def home(request):
    '''
    home page
    '''
    form = FilterForm()
    return render(request, 'snap_test_2/home.html', {'form':form})

def get_places(request):
    '''
    filters places based on ajax call
    optional inputs: bounding box, filters on price level, retailer type and rating
    returns: query set with location information (lat/lon and details)
    '''
    sw_lon = request.GET.get('sw_lon',None)
    sw_lat = request.GET.get('sw_lat',None)
    ne_lon = request.GET.get('ne_lon',None)
    ne_lat = request.GET.get('ne_lat',None)
    
    form_data = dict(request.GET)
    
    price_levels = []
    categories = []
    min_rating = 0
    double = []
    # extract form data from dictionary; unique formatting requires extra work
    for i in range(0,14):
        if form_data.get('data['+str(i)+'][name]') is not None:
            if form_data['data['+str(i)+'][name]'][0] == 'price':
                price_levels.append(form_data['data['+str(i)+'][value]'][0])
            elif form_data['data['+str(i)+'][name]'][0] == 'retailer_type':
                categories.append(form_data['data['+str(i)+'][value]'][0])
            elif form_data['data['+str(i)+'][name]'][0] == 'rating':
                rating = float(form_data['data['+str(i)+'][value]'][0])
                if rating > min_rating:
                    min_rating = rating
            elif form_data['data['+str(i)+'][name]'][0] == 'double_value':
                double = ['Yes']
    # default lists for filters: include all
    if price_levels == []:
        price_levels = SnapLocations.objects.values_list('price_level').distinct() 
    if categories == []:
        categories = SnapLocations.objects.values_list('store_category').distinct() 
    if double == []:
        double = SnapLocations.objects.values_list('double_value').distinct()  
    viewport = pa.get_viewport_poly((sw_lon, sw_lat, ne_lon, ne_lat))
    data = {"data": serialize('geojson',SnapLocations.objects.filter(geom__contained = viewport).filter(price_level__in = price_levels).filter(store_category__in = categories).filter(double_value__in = double).filter(rating__gte = min_rating))}

    return JsonResponse(data)

def submit_grocery_list(request, store_id):
    '''
    grocery list base page
    input: store_id (from url)
    '''

    if request.method == "POST":
        form = GroceryForm(request.POST)     
    else:
        form = GroceryForm()

    store_name = SnapLocations.objects.get(store_id=store_id)
    store_address = SnapLocations.objects.get(store_id=store_id).address

    return render(request, 'snap_test_2/grocery_list_2.html', {'form': form, \
        'store_name': store_name, 'address': store_address, 'store_id': store_id})

def cash_register(request):
    '''
    returns prices to ajax call 
    (input: food_id and store_id)
    '''
    food_id = request.GET.get('food_id', None)
    store_id = request.GET.get('store_id', None)
    price_estimate = pricesAPI.get_price_estimate(store_id,food_id)
    
    data = {
            'food_price': price_estimate,
            'food_quantity': FoodPrices.objects.get(id=food_id).food_quantity,
            'food_name': FoodPrices.objects.get(id=food_id).food_name
            }

    return JsonResponse(data)

def update_price(request):
    '''
    updates database prices based on user input 
    (input: food_id, store_id and a price)
    returns "out of bounds error" or False (0)
    '''
    food_id = request.GET.get('food_id', None)
    store_id = request.GET.get('store_id', None)
    user_price = request.GET.get('user_price',None)

    data = {'bounds_error': 0}

    if pricesAPI.update_price_estimate(store_id,food_id,user_price):
        data['bounds_error'] = 'out of bounds error'

    return JsonResponse(data)


def submit_prices(request, store_id, food_string=0):
    '''
    site to submit user prices to model prepopulated with grocery list

    input: store_id (from url)
    food_string (from url) 
    '''
    if request.method == "POST":
        form = GroceryForms(request.POST)
    else:
        form = GroceryForm()

    store_name = SnapLocations.objects.get(store_id=store_id)
    store_address = SnapLocations.objects.get(store_id=store_id).address
    food_id_list = food_string.split('&')
    food_list = []

    for food_id in food_id_list:
        food = FoodPrices.objects.get(id=food_id).food_name
        food_list.append(food)


    return render(request, 'snap_test_2/submit-prices.html', {'form': form, \
        'store_name': store_name, 'address': store_address, 'food_list': food_id_list, 'store_id': store_id})


def submit_prices_blank(request, store_id):
    '''
    site to submit user prices to model (no grocery list)

    input: store_id (from url)
    '''
    

    if request.method == "POST":
        form = GroceryForms(request.POST)
    else:
        form = GroceryForm()

    store_name = SnapLocations.objects.get(store_id=store_id)
    store_address = SnapLocations.objects.get(store_id=store_id).address
    food_list = []

    return render(request, 'snap_test_2/submit-prices.html', {'form': form, \
        'store_name': store_name, 'address': store_address, 'food_list': food_list, 'store_id': store_id})

baby_snap_2/snap_test_2/templates/snap_test_2/grocery_list_2.html
{% load staticfiles %}

<head>

  <link rel="stylesheet" type="text/css" href="{% static "snap_test_2/css/groceries.css" %}"/>
  <link href="https://fonts.googleapis.com/css?family=Pacifico|Slabo+27px|Source+Sans+Pro:400,900" rel="stylesheet">
  <title>Build your grocery list</title>

</head>

        <div class="menu">
            
            <a class="menu-header" href="/home">snapmap</a>
            <p id = "store_name"> {{store_name}} </p>
            <p id = "store_address"> {{address}} </p>
            <p id = "heading">Build your grocery list:</p>

            <form name ='nameform' class="grocery-form" method='POST' onsubmit='return false' value="Select a food">

                {% csrf_token %}
                {{ form.as_p }}

            </form>

        </div>

    <div id="main">

        <div class="grid">
            <table>
                <col width="269">
                <col width="80">
                <col width="78">
                <col width="85">
                <col width="106">
                <col width="32">
                
                <thead>
                    <tr>
                        <th>Food</th>
                        <th>Price</th>
                        <th>Total</th>
                        <th>Quantity</th>
                        <th></th><th></th>
                    </tr>
                </thead>
            </table>
        </div>
                
        <div class="grid">
            <table id="food_list_table">
                <col width="269">
                <col width="80">
                <col width="78">
                <col width="85">
                <col width="106">
                <col width="32">
            </table>
        </div>

        <table class = 'bottom'>
            <tr>
                <td>Total:</td>
                <td id='total'>&nbsp;&nbsp;$0.00</td>
            </tr>
                    
        </table>

        <input type="submit" value="contribute prices" id="contribute-btn">

    </div>


<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src = {% static "snap_test_2/js/grocerypage.js" %}></script>

<script>

//send list to submit prices page
  $('#contribute-btn').click(function () {
  var food_string = food_ids.join('&');
  if (food_string.length == 0) {
    var url = '/submit-prices/' + '{{store_id}}' + '/'
  }

  else {
  var url = '/submit-prices/' + '{{store_id}}' + '/' + food_string + '/'};
  window.location.href = url; 
});

  //get data based on selected food
$('#id_food, #id_other, #id_grains, #id_dairy, #id_meat_and_fish, #id_fruits_and_veggies').change(function () {
    var food_id = $(this).val();
    var store_id = {{ store_id }};
    console.log("I triggered a changed food list item")
    $.ajax({
        url: '/ajax/cash_register/',

        data: {'food_id': food_id, 
               'store_id': store_id},
        dataType: 'json',
        success: function(data) {
            addFoodtoTable(data, food_id);
            food_ids.push(food_id);
            }
        });
});

</script>

baby_snap_2/snap_test_2/templates/snap_test_2/home.html
<!-- http://howcanisolve.com/33907/django-google-place-autocomplete-address-form -->

{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Snapmap</title>
        <link rel="stylesheet" type="text/css" href="{% static "snap_test_2/css/mappage.css" %}" />
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
        <meta charset="utf-8">
        <link type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500|Pacifico|Slabo+27px|Source+Sans+Pro:400,900" rel="stylesheet">
  </head>

  <body>
    <div id="map"></div>
    <div id='sidebar'>
      <a id="menu-header" href="#">snapmap</a>
        <div id="title">
        Find locations near:
        </div>
        <div id="pac-container">
            <input id="pac-input" type="text"
                placeholder="Enter a location">
        </div>   
        <div id="filters">
            <form id="form" onsubmit='return false'>
                <!--{% csrf_token %}-->
                <table class="form">
                <p class='field'> Retailer Type:<p> {% for field in form.retailer_type %}
                {{ field }}
                {% endfor %}</p>
                <p class='field'>Cost level:<p> {% for field in form.price %}
                {{ field }}
                {% endfor %}</p>
                <p class='field'> Minimum Rating:<p> {% for field in form.rating %}
                {{ field }}
                {% endfor %}</p>
                <p class='field'> Double Value Coupon Program <br /> (farmers markets only):<p> {% for field in form.double_value %}
                {{ field }}
                {% endfor %}</p>
                </table>
                <input type="submit"  value="Filter results" id="filter-btn" />
            </form>
          </div>
          <div id="listing">
            <table id="resultsTable">
             <tbody id="results"></tbody>
            </table>
         </div>
    </div>

    <div style="display: none">
      <div id="info-content">
        <p id = "iw-name"></p>
        <table id='left_table'>
          <col width="85">
          <col width="250">

          <tr id="iw-address-row" class="iw_table_row">
            <td class="iw_attribute_name">Address:</td>
            <td id="iw-address"></td>
           
          </tr>
          <tr id="iw-phone-row" class="iw_table_row">
            <td class="iw_attribute_name">Telephone:</td>
            <td id="iw-phone"></td>
            
          </tr>
          <tr id="iw-category-row" class="iw_table_row">
            <td class="iw_attribute_name">Category:</td>
            <td id="iw-category"></td>
          </tr>
          <tr id="iw-rating-row" class="iw_table_row">
            <td class="iw_attribute_name">Rating:</td>
            <td id="iw-rating"></td>
          </tr>
          <tr id="iw-website-row" class="iw_table_row">
            <td class="iw_attribute_name">Website:</td>
            <td id="iw-website"></td>
          </tr>
          
          <tr id="iw-double-row" class="iw_table_row">
            <td class="iw_attribute_name">Double Value:</td>
            <td id="iw-double"></td>
          </tr>
        
        </table>

        <table id='right_table'>
          <col width="50">
          <col width="190">
          <tr id="iw-hours-row" class="iw_table_row">
            <td class="iw_attribute_name">Hours:</td>
            <td id="iw-hours"></td>
          </tr>
        </table>
      </div>
    </div>
    
    <!--     SCRIPTS BEGIN  -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD2zsB1fPiX_9LUi7t_hyA_TaY3E2aAPQU&libraries=places"></script>
    <script>
    //Much of the marker placing js code is adapted from the google example.
    //We made major customizations to add ajax capabilities and have also
    //made many stylistic adjustments.
    //https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-hotelsearch
    var map
    var placeSearch, autocomplete, infoWindow;
    
    var markers = [];
    var MARKER_PATH = 'https://developers.google.com/maps/documentation/javascript/images/marker_green';

    $("#autocomplete").on('focus', function () {
          geolocate();
        });
  
    //Map initialization modified from:
    //https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete
    function initialize() {
        console.log("I JUST RESET THE MAP")
        map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: new google.maps.LatLng(41.913154, -87.633311),
          });

        var card = document.getElementById('pac-card');
        var input = document.getElementById('pac-input');
        var types = document.getElementById('type-selector');
        var resultsBox = document.getElementById('listing');
        //map.controls[google.maps.ControlPosition.TOP_RIGHT].push(card);
        
      // Create the autocomplete object
       autocomplete = new google.maps.places.Autocomplete(
        document.getElementById('pac-input'));
        
        infoWindow = new google.maps.InfoWindow({
          content: document.getElementById('info-content')
        });

        // When the user selects an address from the dropdown,
       // populate the address fields in the form.
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
          var place = autocomplete.getPlace();
          if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
          } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);  
          }
           var data = $('#form').serializeArray();
           get_places(data);
        });

      
        $("#form").on("submit", function(){
          var data = $(this).serializeArray();
          get_places(data);
        });

      }
        
      //https://simpleisbetterthancomplex.com/tutorial/2016/08/29/how-to-work-with-ajax-request-with-django.http
      // This site taught us how to use ajax with django.
      function get_places(data) {
          var bounds = map.getBounds().toJSON();
          var sw_lat = bounds.south;
          var sw_lon = bounds.west;
          var ne_lat = bounds.north;
          var ne_lon = bounds.east;  
          
          $.ajax({
            url: '/ajax/get_places/',
            data: { 'data': data,
                    'sw_lat':sw_lat,
                    'sw_lon':sw_lon,
                    'ne_lat':ne_lat,
                    'ne_lon':ne_lon
                  },
            dataType: 'json',
            success: function(data) {
              
            var results = JSON.parse(data.data).features;
            placeMarkers(results);
            }
          });
        }
    var markers = [];
    var MARKER_PATH = 'https://developers.google.com/maps/documentation/javascript/images/marker_green';


    function placeMarkers(results){
      clearMarkers();
      clearResults();
      // Create a marker for each hotel found, and
      // assign a letter of the alphabetic to each marker icon.
      for (var i = 0; i < results.length; i++) {

        var type = results[i].properties.store_category;
          
        var markerIcon = ''
        markerIcon = selectIcon(type);

        // Use marker animation to drop the icons incrementally on the map.
        markers[i] = new google.maps.Marker({
        position: new google.maps.LatLng(results[i].geometry.coordinates[1], results[i].geometry.coordinates[0]),
        animation: google.maps.Animation.DROP,
        icon: markerIcon
        });
        
        markers[i].placeResult = results[i];
        google.maps.event.addListener(markers[i], 'click', showInfoWindow);
        setTimeout(dropMarker(i), 0);
        addResult(results[i], i);
          }
      }

    function selectIcon(type){
      if (type == "Grocery") {
          var markerIcon = 'http://i.imgur.com/gyu9sDb.png'
        } else if (type == "Farmer's Market") {
          var markerIcon = 'http://i.imgur.com/wOJFQEz.png'
        } else if (type == "Convenience Store") {
          var markerIcon = 'http://i.imgur.com/xBkWn0a.png'
        } else if (type == "Gas Station") {
          var markerIcon = 'http://i.imgur.com/OvKr766.png'
        } else if (type == "Other" || type == "Not available") {
          var markerIcon = 'http://i.imgur.com/UyipNwG.png'
        }
        return markerIcon;
    }

    function selectIconForList(type){
      if (type == "Grocery") {
          var markerIcon = 'http://i.imgur.com/2U1kUPJ.png'
        } else if (type == "Farmer's Market") {
          var markerIcon = 'http://i.imgur.com/dtjndbn.png'
        } else if (type == "Convenience Store") {
          var markerIcon = 'http://i.imgur.com/ey3Gjry.png'
        } else if (type == "Gas Station") {
          var markerIcon = 'http://i.imgur.com/jO4tKLq.png'
        } else if (type == "Other" || type == "Not available") {
          var markerIcon = 'http://i.imgur.com/LZNaYUi.png'
        }
        return markerIcon;
    }


    function clearMarkers() {
      for (var i = 0; i < markers.length; i++) {
        if (markers[i]) {
          markers[i].setMap(null);
        }
      }
          markers = [];
      }

    function dropMarker(i) {
      return function() {
        markers[i].setMap(map);
      };}

    function geolocate() {
      if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function (position) {
            var geolocation = new google.maps.LatLng(
            position.coords.latitude, position.coords.longitude);

            var latitude = position.coords.latitude;
            var longitude = position.coords.longitude;
            document.getElementById("latitude").value = latitude;
            document.getElementById("longitude").value = longitude;
            autocomplete.setBounds(new google.maps.LatLngBounds(geolocation, geolocation));
      });}
      }


    function addResult(result, i) {
      var results = document.getElementById('results');
      var type = result.properties.store_category;
      var markerIcon = selectIconForList(type);

      var tr = document.createElement('tr');
      tr.style.width = '100%' ;
      //tr.style.backgroundColor = (i % 2 === 0 ? '#F0F0F0' : '#FFFFFF');
      tr.id = (i % 2 === 0 ? 'gray-row' : 'white-row');
      tr.onclick = function() {
        google.maps.event.trigger(markers[i], 'click');
      };

      var iconTd = document.createElement('td');
      var nameTd = document.createElement('td');
      var icon = document.createElement('img');
      icon.src = markerIcon;
      icon.setAttribute('class', 'placeIcon');
      icon.setAttribute('className', 'placeIcon');
      var name = document.createTextNode(result.properties.store_name);
      iconTd.appendChild(icon);
      nameTd.appendChild(name);
      tr.appendChild(iconTd);
      tr.appendChild(nameTd);
      results.appendChild(tr);
    }

    function showInfoWindow() {
    var marker = this;
    infoWindow.open(map, marker);
    var place = marker.placeResult.properties;
    buildIWContent(place);
    }

    function clearResults() {
      var results = document.getElementById('results');
      while (results.childNodes[0]) {
        results.removeChild(results.childNodes[0]);
      }
    }

  
    function buildIWContent(place) {
      var rating = place.rating;
      if (rating == 0) {
            rating = 'Not available';
          }; 
      document.getElementById('iw-name').innerHTML = place.store_name + '<input type="submit" id = "submit_groceries" name = "submit_groceries" value="Build Grocery List" />' + '<input type="submit" id = "submit_prices" name = "submit_prices" value="Contribute Prices" />';
      document.getElementById('iw-address').textContent = place.address;  
      document.getElementById('iw-phone').textContent = place.phone;
      document.getElementById('iw-rating').textContent = rating;
      if (place.website == "Not available"){
        document.getElementById('iw-website').textContent = place.website;
      } else {
      document.getElementById('iw-website').innerHTML = '<a href="' + place.website +'"> website</a>';};
      document.getElementById('iw-hours').textContent = place.hours;
      document.getElementById('iw-category').textContent = place.store_category;
      document.getElementById('iw-double').textContent = place.double_value;
      

      $('#submit_groceries').click(function() {
      var store_id = place.store_id;
      var url = '/groceries/' + store_id + '/';
      window.location.href = url;
      }); 
    

    $('#submit_prices').click(function() {
      var store_id = place.store_id;
      var url = '/submit-prices/' + store_id + '/';
      window.location.href = url;
      }); 
    }
    
    initialize();
    </script>

  </body>
</html>

baby_snap_2/snap_test_2/templates/snap_test_2/submit-prices.html
{% load staticfiles %}

<head>
  
  <link rel="stylesheet" type="text/css" href="{% static "snap_test_2/css/groceries.css" %}"/>
  <link href="https://fonts.googleapis.com/css?family=Pacifico|Slabo+27px|Source+Sans+Pro:400,900" rel="stylesheet">
  <title>Submit your prices</title>

</head>

  <div class="menu">

    <a class="menu-header" href="/home">snapmap</a>
    <p id = "store_name"> {{store_name}} </p>
    <p id = "store_address"> {{address}} </p>
    <p id = "heading">Contribute prices:</p>
    
    <form name ='nameform' class="grocery-form" method='POST' onsubmit='return false' value="Select a food">

        {% csrf_token %}
        {{ form.as_p }}

    </form>

  </div>

  <div id="main">

    <div class="grid">
      <table>
        <col width="300">
        <col width="145">
        <col width="115">
        <col width="110">
        <col width="30">
        
        <thead>
          <tr>
            <th>Food</th>
            <th>Current Price</th>
            <th>Your Price</th>
            <th></th>
          </tr>
        </thead>
      </table>
    </div>
    
    <div class="grid">
      <table id="food_list_table">
        <col width="300">
        <col width="145">
        <col width="115">
        <col width="110">
        <col width="30">
      </table>
    </div>

  </div>

<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src = {% static "snap_test_2/js/submitpricespage.js" %}></script>

<script>

//prepopulate table with foods from grocery list page
$(window).on('load', function () {
  var foods = {{food_list|safe}};
  var foods_length = foods.length
  var store_id = {{store_id}};

  for (var i = 0; i < foods_length; i++) {

    var food_id = foods[i]

    $.ajax({
      url: '/ajax/cash_register/',
      data: {'food_id': food_id, 'store_id': store_id},
      dataType: 'json',
      success: function(data) {
        addFoodtoTable(data, food_id);
      }
    })
  }
});


//get data based on selected food
$('#id_food, #id_other, #id_grains, #id_dairy, #id_meat_and_fish, #id_fruits_and_veggies').change(function () {

    var food_id = $(this).val();
    var store_id = {{store_id}}


    $.ajax({
        url: '/ajax/cash_register/',
        data: {'food_id': food_id, 'store_id': store_id},
        dataType: 'json',
        success: function(data) {
            addFoodtoTable(data, food_id);
            }
        });
});


$('#food_list_table').on('click', '#checkmark', function () {
    //get row id for the selected row
    var rc = $(this).parent().parent().attr('id');

    //get the user input value from that row 
    var price = document.querySelectorAll('.price_input')[rc].value;

    //ensure that the input is integer or float
    if ($.isNumeric(price) == false) {
        alert('please enter a number :-)\ne.g. 4 or 4.00')
    } 

    //replace the submit field with a smiley after submission
        var food_id = $(this).parent().next('td').text();
        var store_id = {{store_id}};

    $.ajax({

        url: '/ajax/update_price/',
        data: {'food_id': food_id, 'store_id': store_id, 'user_price': price},
        dataType: 'json',
        success: function(data) {
          if (data.bounds_error == "out of bounds error") {
            alert('This price is out of bounds')
          } else {
          var table_rows = document.getElementById('food_list_table').rows;
          var table_cells = table_rows[rc].cells;
          var cell = table_cells[2]
          cell.innerHTML = '<img src= "http://i.imgur.com/2MzKVnC.png" class="price_input" id="smiley">'}
           } 
});

});

</script> 